name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'projects/**/*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm i --force
      - name: Build Form Builder
        run: npm run build:form-builder
      - name: Copy Form Builder
        run: rm -rf node_modules/@jaspero/form-builder && cp -r dist/@jaspero/form-builder node_modules/@jaspero/form-builder
      - name: Build Fields
        run: npm run build:fields-mat
      - name: Copy Fields
        run: rm -rf node_modules/@jaspero/fb-fields-mat && cp -r dist/@jaspero/fb-fields-mat node_modules/@jaspero/fb-fields-mat
      - name: Build Segments
        run: npm run build:segments-mat
      - name: Copy Fields
        run: rm -rf node_modules/@jaspero/fb-segments-mat && cp -r dist/@jaspero/fb-segments-mat node_modules/@jaspero/fb-segments-mat
      - name: Build Plugins
        run: npm run build:libraries
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
